name: Build (daily)

on:
  schedule:
    # daily at 3:24 UTC
    - cron: "24 3 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  common:
    uses: ./.github/workflows/build-common.yml
    secrets:
      FLAKY_TEST_REPORTER_ACCESS_KEY: ${{ secrets.FLAKY_TEST_REPORTER_ACCESS_KEY }}

  test-latest-deps:
    uses: ./.github/workflows/reusable-test-latest-deps.yml
    secrets:
      FLAKY_TEST_REPORTER_ACCESS_KEY: ${{ secrets.FLAKY_TEST_REPORTER_ACCESS_KEY }}

  muzzle:
    uses: ./.github/workflows/reusable-muzzle.yml

  shell-script-check:
    uses: ./.github/workflows/reusable-shell-script-check.yml

  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: jdx/mise-action@e3d7b8d67a7958d1207f6ed871e83b1ea780e7b0 # v3.3.1

      - run: mise run lint:links
        env:
          GITHUB_TOKEN: ${{ github.token }}

  markdown-lint-check:
    uses: ./.github/workflows/reusable-markdown-lint-check.yml

  misspell-check:
    uses: ./.github/workflows/reusable-misspell-check.yml

  workflow-notification:
    permissions:
      contents: read
      issues: write
    needs:
      - common
      - test-latest-deps
      - muzzle
      - link-check
      - misspell-check
    if: always()
    uses: ./.github/workflows/reusable-workflow-notification.yml
    with:
      success: >-
        ${{
          needs.common.result == 'success' &&
          needs.test-latest-deps.result == 'success' &&
          needs.muzzle.result == 'success' &&
          needs.link-check.result == 'success' &&
          needs.misspell-check.result == 'success'
        }}
